apiVersion: v1
kind: Service
metadata: 
  name: db
spec: 
  selector: 
    app: mysql-pod
  ports:
    - port: 3306
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: mysql
        - name: MYSQL_PASSWORD
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          value: supersecret
---
apiVersion: v1
kind: Service
metadata: 
  name: webapp
spec: 
  selector: 
    app: webapp-pod
  ports:
    - port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-pod
    spec:
      containers:
      - name: webapp
        image: arungupta/docker-javaee:dockerconeu17
        ports:
        - containerPort: 8080
